# application.properties
spring.application.name=blinkdrive

# Server configuration
server.port=8080

# RMI client configuration
auth.rmi.host=localhost
auth.rmi.port=1099
auth.rmi.service-name=AuthService

# Database server connection
database.server.url=http://localhost:3000

# Storage configuration
blinkdrive.storage.replication.count=2

# Health check interval (in milliseconds)
blinkdrive.health-check.interval=60000